### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by RegaMadila** [Mysteriza/flipIR-cloner#2]
can you share the wiring diagram, i have an assignment that similiar to yours

**Comment by Mysteriza** [comment]
[FlipIR Cloner Wiring Diagram.pdf](https://github.com/Mysteriza/flipIR-cloner/files/13457991/FlipIR.Cloner.pdf)

Check this out.

**Comment by RegaMadila** [comment]
Thanks  bro, really help meout
